# Generated by Django 4.2.7 on 2023-11-27 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('answer', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hunt',
            name='number_of_skips_for_each_team',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('remaining_skips', models.IntegerField(default=3)),
                ('joining_password', models.CharField(blank=True, max_length=100, null=True)),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.hunt')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_lead_by', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleTimeMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_start_time', models.DateTimeField()),
                ('puzzle_end_time', models.DateTimeField()),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_maintenance', to='api.puzzle')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_maintenance', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.puzzle')),
            ],
        ),
        migrations.AddField(
            model_name='puzzle',
            name='hunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='api.hunt'),
        ),
    ]
