# Generated by Django 4.2.7 on 2023-11-27 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_puzzle_hunt_number_of_skips_for_each_team_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='participants',
            field=models.ManyToManyField(related_name='participating_hunts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='organizers',
            field=models.ManyToManyField(related_name='organizing_hunts', to=settings.AUTH_USER_MODEL),
        ),
    ]
