# Generated by Django 4.2.7 on 2023-11-30 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hunt_participants_alter_hunt_organizers'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='current_puzzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_puzzle', to='api.puzzle'),
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='solved_puzzles',
            field=models.ManyToManyField(blank=True, related_name='solved_by_teams', to='api.puzzle'),
        ),
        migrations.AddField(
            model_name='team',
            name='viewed_puzzles',
            field=models.ManyToManyField(blank=True, related_name='given_to_teams', to='api.puzzle'),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participating_hunts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HuntImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.hunt')),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='api.puzzle')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='api.hunt')),
            ],
        ),
    ]
