# Generated by Django 4.2.7 on 2023-11-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_puzzle_points_team_current_puzzle_team_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzletimemaintenance',
            name='puzzle_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puzzletimemaintenance',
            name='puzzle_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
