# Generated by Django 4.2.7 on 2023-12-06 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_puzzletimemaintenance_puzzle_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.hunt')),
            ],
        ),
    ]
