# Generated by Django 4.2.7 on 2023-12-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_announcement_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='created_at',
        ),
    ]
