# Generated by Django 4.2.7 on 2023-12-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_rule_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='puzzle_order_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
