# Generated by Django 4.2.7 on 2023-12-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_team_puzzle_order_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='current_puzzle_index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
