# Generated by Django 4.2.7 on 2023-12-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_team_current_puzzle_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hunt',
            name='payment_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
