# Generated by Django 4.2.7 on 2023-12-23 13:44

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_hunt_payment_completed_hunt_payment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='images/'),
        ),
    ]
