# Generated by Django 4.2.7 on 2023-12-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_huntimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
