# Generated by Django 4.2.7 on 2023-12-23 13:48

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_huntimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=50, scale=None, size=[1920, 1080], upload_to='images/'),
        ),
    ]
